site_name: NP Practice Resource
site_url: https://nppr.jgrafe.synology.me  # Crucial for PWA features
site_description: A clinical resource for BC NPs.
site_favicon: assets/favicon.ico

extra_css:
  - assets/extra.css
  
theme:
  name: material
  logo: assets/logo.png # Or path to image: assets/logo.png
  palette: 
    primary: teal
    accent: indigo
  
  # 3. Define the Favicon (The App Icon on the phone
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    # Mobile features
    - navigation.top      # "Back to Top" button
    - navigation.tracking # Highlights where you are in the doc

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - offline # <--- This enables "Service Workers" to cache the site

#nav:
  #- Home: index.md
  # MkDocs will automatically discover other files, or you can list them here
